bib_index = {
    'UbuntuDialogueCorpus': 'DBLP:conf/sigdial/LowePSP15',
    'HRED': 'DBLP:conf/aaai/SerbanSBCP16',
    'VHRED': 'DBLP:journals/corr/SerbanSLCPCB16',
    'ADEM': 'DBLP:conf/acl/LoweNSABP17',
    'Ruber': 'DBLP:conf/aaai/TaoMZY18',
    'HowNOT': 'DBLP:conf/emnlp/LiuLSNCP16',
    'opensub': 'DBLP:conf/lrec/LisonT16',
    'Seq2Seq': 'DBLP:journals/corr/VinyalsL15',
    'GoogleChatbot': 'DBLP:journals/corr/VinyalsL15',
    'LSDSCC': 'DBLP:conf/naacl/XuJLRWWWW18',
    'Ritter11': 'Ritter:2011:DRG:2145432.2145500',
    'NNLM': 'DBLP:journals/jmlr/BengioDVJ03',
    'RNNLM': 'DBLP:conf/interspeech/MikolovKBCK10',
    'LSTM': 'DBLP:journals/neco/HochreiterS97',
    'GRU': 'DBLP:conf/emnlp/ChoMGBBSB14',
    'B-Attention': 'DBLP:journals/corr/BahdanauCB14',
    'L-Attention': 'DBLP:conf/emnlp/LuongPM15',
    'BiRNN': 'DBLP:journals/tsp/SchusterP97',
    'DiverseBeam': 'DBLP:journals/corr/LiMJ16',
    'BLEU': 'DBLP:conf/acl/PapineniRWZ02',
    'NIST': 'Doddington:2002:AEM:1289189.1289273',
    'METEOR': 'DBLP:conf/acl/BanerjeeL05',
    'ROUGE': 'W04-1013',
    'CHRF': 'DBLP:conf/wmt/Popovic15',
    'TER': 'Snover2005ASO',
    'BEER': 'DBLP:conf/wmt/StanojevicS14',
    'NUC': 'DBLP:conf/sigdial/LoweSNCP16',
    'DCGM': 'DBLP:journals/corr/SordoniGABJMNGD15',
    'deltaBLEU': 'DBLP:conf/acl/GalleyBSJAQMGD15',
    'distributed_hypothesis': 'harris54',
    'MMI': 'DBLP:conf/naacl/LiGBGD16',
    'Distill': 'DBLP:journals/corr/LiMJ17a',
    'BLEU-Smooth': 'DBLP:conf/wmt/ChenC14',
}

urls = {
    'ubuntu_irc': 'http://irclogs.ubuntu.com',
    'opensubtitles': 'http://www.opensubtitles.org',
}
