bib_index = {
    'UbuntuDialogueCorpus': 'DBLP:conf/sigdial/LowePSP15',
    'HRED': 'DBLP:conf/aaai/SerbanSBCP16',
    'VHRED': 'DBLP:journals/corr/SerbanSLCPCB16',
    'ADEM': 'DBLP:conf/acl/LoweNSABP17',
    'Ruber': 'DBLP:conf/aaai/TaoMZY18',
    'HowNOT': 'DBLP:conf/emnlp/LiuLSNCP16',
    'opensub': 'DBLP:conf/lrec/LisonT16',
    'Seq2Seq': 'DBLP:journals/corr/VinyalsL15',
    'LSDSCC': 'DBLP:conf/naacl/XuJLRWWWW18',
    'Ritter11': 'Ritter:2011:DRG:2145432.2145500',
    'NNLM': 'DBLP:journals/jmlr/BengioDVJ03',
    'RNNLM': 'DBLP:conf/interspeech/MikolovKBCK10',
    'LSTM': 'DBLP:journals/neco/HochreiterS97',
    'GRU': 'DBLP:conf/emnlp/ChoMGBBSB14',
    'B-Attention': 'DBLP:journals/corr/BahdanauCB14',
    'L-Attention': 'DBLP:conf/emnlp/LuongPM15',
    'BiRNN': 'DBLP:journals/tsp/SchusterP97',
}
